### ISSUE TITLE
windows执行时报错：UnicodeDecodeError: 'gbk'

### ISSUE THREAD

**Issue by yhao-z** [lidongj/yqxx#3]
报错： UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 10: illegal multibyte sequence

打开anaconda目录下的anaconda\lib\site-packages\yqxx\yqxx.py文件
把第23行o = open(filename, 'r')
改成o = open(filename, 'r', encoding='utf-8')
就可以了

（可能是因为作者的开发环境不一样？mac上没问题，win上就没办法执行了）
（不是计算机专业，原理不太懂）
（btw，作者牛逼！人类之光啊！）

**Comment by billchenchina** [comment]
已在 [0.2.5](https://github.com/billchenchina/yqxx/releases/tag/0.2.5) 修复。
